### ISSUE TITLE
mongoで設定ファイルが反映されていない

### ISSUE THREAD

**Issue by t-uekawa-n** [exastro-suite/exastro-helm#88]
ITA2.5.2時点で、helmで、mongoの設定ファイルが反映されていない。

下記のようにcommandを入れると、読み込まれたように見えるが
MONGO_INITDB_ROOT_USERNAME
MONGO_INITDB_ROOT_PASSWORD
がきいていないようにみえる。

exastro-helm-beta/charts/exastro-platform/charts/mongo/templates/statefulset.yaml
```
      containers:
      - name: {{ template "mongo.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
```
