### ISSUE TITLE
MariaDBヘルスチェックのオプション修正

### ISSUE THREAD

**Issue by yutoyajimaaa** [exastro-suite/exastro-helm#92]
https://github.com/exastro-suite/exastro-it-automation/issues/2496
上記Issueに伴う、MariaDBのヘルスチェックコマンドのオプション、「--innodb_initialized」を削除する

```
livenessProbe:
 exec:
   command:
   - healthcheck.sh
   - --su-mysql
   - --connect
   - --innodb_initialized #削除対象
 initialDelaySeconds: 30
 periodSeconds: 10
 timeoutSeconds: 3

readinessProbe:
 exec:
   command:
   - healthcheck.sh
   - --su-mysql
   - --connect
   - --innodb_initialized #削除対象
 initialDelaySeconds: 30
 periodSeconds: 10
 timeoutSeconds: 3
```
